"""Add Notification model

Revision ID: 382010b7c8ce
Revises: e1fef9cec5d9
Create Date: 2026-03-08 20:27:51.317320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382010b7c8ce'
down_revision = 'e1fef9cec5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('related_exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
